=== camenduru/ltx-video-tost/schema_i2v.json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "type": "object",
  "properties": {
    "readme": {
      "type": "string",
      "title": "LTX-Video",
      "author": "Lightricks",
      "code": "https://github.com/Lightricks/LTX-Video",
      "page": "https://www.lightricks.com/ltxv",
      "jupyter": "https://github.com/camenduru/ltx-video-tost",
      "api": "https://github.com/camenduru/tost-api-examples/blob/main/v1/ltx-t2v.ipynb",
      "tags": [
        "Text to Video"
      ],
      "widget": "readme"
    },
    "upload": {
      "type": "string",
      "widget": "upload",
      "upload_url": "https://litterbox.catbox.moe/resources/internals/api.php",
      "property": "input_image"
    },
    "input_image": {
      "type": "string",
      "description": "Image URL",
      "widget": "textarea"
    },
    "positive_prompt": {
      "type": "string",
      "description": "Positive Prompt",
      "widget": "textarea"
    },
    "negative_prompt": {
      "type": "string",
      "description": "Negative Prompt",
      "widget": "textarea"
    },
    "frame_rate": {
      "type": "integer",
      "description": "Frame Rate",
      "widget": "hidden"
    },
    "sampler_name": {
      "type": "string",
      "description": "Sampler Name",
      "widget": "hidden"
    },
    "steps": {
      "type": "integer",
      "description": "Steps",
      "widget": "hidden"
    },
    "max_shift": {
      "type": "number",
      "description": "Max Shift",
      "widget": "hidden"
    },
    "base_shift": {
      "type": "number",
      "description": "Base shift",
      "widget": "hidden"
    },
    "stretch": {
      "type": "boolean",
      "description": "Stretch",
      "widget": "hidden"
    },
    "terminal": {
      "type": "number",
      "description": "Terminal",
      "widget": "hidden"
    },
    "width": {
      "type": "integer",
      "description": "Width",
      "widget": "hidden"
    },
    "height": {
      "type": "integer",
      "description": "Height",
      "widget": "hidden"
    },
    "length": {
      "type": "integer",
      "widget": "select",
      "description": "Length (Frames)",
      "oneOf": [
        {
          "description": "97",
          "enum": [
            97
          ]
        },
        {
          "description": "105",
          "enum": [
            105
          ]
        },
        {
          "description": "113",
          "enum": [
            113
          ]
        },
        {
          "description": "121",
          "enum": [
            121
          ]
        },
        {
          "description": "129",
          "enum": [
            129
          ]
        },
        {
          "description": "137",
          "enum": [
            137
          ]
        },
        {
          "description": "145",
          "enum": [
            145
          ]
        },
        {
          "description": "153",
          "enum": [
            153
          ]
        },
        {
          "description": "161",
          "enum": [
            161
          ]
        },
        {
          "description": "169",
          "enum": [
            169
          ]
        },
        {
          "description": "177",
          "enum": [
            177
          ]
        },
        {
          "description": "185",
          "enum": [
            185
          ]
        },
        {
          "description": "193",
          "enum": [
            193
          ]
        },
        {
          "description": "201",
          "enum": [
            201
          ]
        },
        {
          "description": "209",
          "enum": [
            209
          ]
        },
        {
          "description": "217",
          "enum": [
            217
          ]
        },
        {
          "description": "225",
          "enum": [
            225
          ]
        },
        {
          "description": "233",
          "enum": [
            233
          ]
        },
        {
          "description": "241",
          "enum": [
            241
          ]
        },
        {
          "description": "249",
          "enum": [
            249
          ]
        },
        {
          "description": "257",
          "enum": [
            257
          ]
        }
      ],
      "default": 97
    },
    "add_noise": {
      "type": "boolean",
      "description": "Add Noise",
      "widget": "hidden"
    },
    "noise_seed": {
      "type": "integer",
      "description": "Noise Seed (if 0 random)"
    },
    "cfg": {
      "type": "number",
      "description": "CFG",
      "widget": "hidden"
    },
    "fps": {
      "type": "integer",
      "description": "FPS",
      "widget": "hidden"
    },
    "prompt_enhance": {
      "type": "boolean",
      "description": "Prompt Enhance"
    },
    "example": {
      "type": "string",
      "image1": "https://files.catbox.moe/oq8d95.mp4",
      "image2": "https://files.catbox.moe/rry6zz.mp4",
      "image3": "https://files.catbox.moe/um6qm7.mp4",
      "image4": "https://files.catbox.moe/xqg1u3.mp4",
      "video_aspect_ratio": "67%",
      "line1": "Video size: 768x512 pixels",
      "line2": "Video duration: 4 seconds",
      "widget": "example"
    }
  },
  "buttons": [
    {
      "id": "enter",
      "label": "ðŸ¥ª Enter"
    }
  ]
}

=== camenduru/ltx-video-tost/model_i2v.json
{
    "input_image": "https://files.catbox.moe/dag9vz.jpg",
    "positive_prompt": "best quality, 4k, HDR, fireworks",
    "negative_prompt": "low quality, worst quality, deformed, distorted, disfigured, motion smear, motion artifacts, fused fingers, bad anatomy, weird hand, ugly",
    "frame_rate": 25,
    "sampler_name": "euler",
    "steps": 30,
    "max_shift": 2.05,
    "base_shift": 0.95,
    "stretch": true,
    "terminal": 0.10,
    "width": 768,
    "height": 512,
    "length": 97,
    "add_noise": true,
    "noise_seed": 0,
    "cfg": 3.0,
    "fps": 24
}

=== camenduru/ltx-video-tost/model_t2v.json
{
    "positive_prompt": "A woman with long brown hair and light skin smiles at another woman with long blonde hair. The woman with brown hair wears a black jacket and has a small, barely noticeable mole on her right cheek. The camera angle is a close-up, focused on the woman with brown hair's face. The lighting is warm and natural, likely from the setting sun, casting a soft glow on the scene. The scene appears to be real-life footage.",
    "negative_prompt": "low quality, worst quality, deformed, distorted, disfigured, motion smear, motion artifacts, fused fingers, bad anatomy, weird hand, ugly",
    "frame_rate": 25,
    "sampler_name": "euler",
    "steps": 30,
    "max_shift": 2.05,
    "base_shift": 0.95,
    "stretch": true,
    "terminal": 0.10,
    "width": 768,
    "height": 512,
    "length": 97,
    "add_noise": true,
    "noise_seed": 0,
    "cfg": 3.0,
    "fps": 24
}
